sudo: required
services:
  - docker

before_install:
  - docker build -t bqroster/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bqroster/client-test npm run test

after_success:
  - docker build -t bqroster/docker-multicontainer ./client
  - docker build -t bqroster/docker-mc-nginx ./nginx
  - docker build -t bqroster/docker-mc-server ./server
  - docker build -t bqroster/docker-mc-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
  - docker push bqroster/docker-multicontainer
  - docker push bqroster/docker-mc-nginx
  - docker push bqroster/docker-mc-server
  - docker push bqroster/docker-mc-worker